#!/usr/bin/env python3
"""
Script 01: Individual ID Sweep (Crops-Masks Config)
Multi-class classification experiment with varying samples per individual.
Uses crops-masks dataset configuration with detection filtering and temporal splits.
"""

import sys
import os
import argparse
import time
import json
import torch
import numpy as np
from pathlib import Path
from sklearn.metrics import confusion_matrix

# Control parallelism to prevent OOM issues
os.environ["TOKENIZERS_PARALLELISM"] = "false"  # Disable tokenizer parallelism
os.environ["HF_DATASETS_OFFLINE"] = "1"  # Use cached data only

# Assume script is run from wolverines root directory
sys.path.append('.')

from utils.dataset import set_all_seeds, create_dataloaders
from utils.models import create_model
from utils.training import check_result_exists, MultiClassTrainer
from datasets import load_dataset
import torchvision.transforms as T
from PIL import Image

# Configure datasets library to use single process
import datasets
datasets.config.NUM_PROC = 1


def load_feasibility_config():
    """Load the feasibility configuration from script 00"""
    config_path = 'individual_id/results/feasible_individuals.json'
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: {config_path} not found. Please run 00_count_individuals.py first.")
        return None


def get_job_combinations(job_idx: int, max_jobs: int = 24) -> list:
    """Map job index to list of (sample_size, threshold, seed) tuples"""
    
    # Load dynamic parameters from feasibility config
    config = load_feasibility_config()
    if config is None:
        return []
    
    # Get training sizes from config (generated by script 00)
    sample_sizes = config.get('training_sizes', [1, 2, 4, 8, 16, 32, 64])
    thresholds = ['threshold_0.0', 'threshold_0.2', 'threshold_0.4', 'threshold_0.6', 'threshold_0.8']  # 5 thresholds
    seeds = [0, 1, 2, 3, 4, 5, 6, 7]  # 8 seeds
    
    # Generate all combinations: len(sample_sizes) × 5 thresholds × 8 seeds
    all_combinations = []
    for sample_size in sample_sizes:
        for threshold in thresholds:
            for seed in seeds:
                all_combinations.append((sample_size, threshold, seed))
    
    total_combinations = len(all_combinations)
    
    # Handle case where job_idx exceeds available jobs or no combinations
    if job_idx >= max_jobs or total_combinations == 0:
        return []
    
    # Dynamic job distribution: handle any number of combinations
    configs_per_job = total_combinations // max_jobs
    remainder = total_combinations % max_jobs
    
    # Jobs 0 to (remainder-1) get one extra config to handle remainder
    if job_idx < remainder:
        start_idx = job_idx * (configs_per_job + 1)
        end_idx = start_idx + configs_per_job + 1
    else:
        start_idx = remainder * (configs_per_job + 1) + (job_idx - remainder) * configs_per_job
        end_idx = start_idx + configs_per_job
    
    # Handle case where this job has no work (total_combinations < max_jobs)
    if start_idx >= total_combinations:
        return []
    
    # Ensure we don't exceed the total combinations
    end_idx = min(end_idx, total_combinations)
    
    return all_combinations[start_idx:end_idx]


def load_reidentification_dataset():
    """Load the wolverines dataset with reidentification configuration"""
    print("Loading wolverines dataset (reidentification config)...")
    dataset = load_dataset("kdoherty/wolverines", "reidentification", split="train")
    print(f"Loaded {len(dataset)} samples from reidentification config")
    return dataset


def create_quality_threshold_dataset(dataset, individuals, sample_size, threshold_approach, seed, validation_config):
    """Create quality-threshold based train/val splits with unified validation set across all thresholds"""
    import random
    from collections import defaultdict
    
    random.seed(seed)
    np.random.seed(seed)
    
    # Extract threshold value from approach name (e.g., 'threshold_0.8' -> 0.8)
    threshold_value = float(threshold_approach.split('_')[1])
    
    print(f"Creating quality threshold dataset: {sample_size} samples per class, training threshold≥{threshold_value:.1f}")
    
    # Convert dataset to DataFrame for easier processing (indices and metadata only)
    data_list = []
    for i, sample in enumerate(dataset):
        data_list.append({
            'index': i,
            'id': sample['id'],
            'ymdh': sample['ymdh'],
            'pelage_score': sample['pelage_score']
            # Removed 'sample': sample to prevent storing image data in memory
        })
    
    import pandas as pd
    df = pd.DataFrame(data_list)
    
    # Build unified validation set with threshold membership tracking
    all_val_indices = set()
    val_threshold_memberships = {}  # Maps dataset_idx -> list of thresholds
    
    print("Building unified validation set across all thresholds...")
    for val_threshold in [0.8, 0.6, 0.4, 0.2, 0.0]:
        val_threshold_key = f'threshold_{val_threshold:.1f}'
        
        for individual_id in individuals:
            if val_threshold_key in validation_config['validation_indices'][individual_id]:
                val_data = validation_config['validation_indices'][individual_id][val_threshold_key]
                frozen_val_indices = val_data['indices']
                
                # Map pandas indices to dataset indices for this threshold
                ind_data = df[df['id'] == individual_id]
                
                for val_idx in frozen_val_indices:
                    # Find the dataset index that corresponds to this pandas index
                    matching_rows = ind_data[ind_data.index == val_idx]
                    if len(matching_rows) == 1:
                        dataset_idx = int(matching_rows.iloc[0]['index'])  # Convert to Python int for JSON serialization
                        all_val_indices.add(dataset_idx)
                        
                        # Track which thresholds this sample belongs to
                        if dataset_idx not in val_threshold_memberships:
                            val_threshold_memberships[dataset_idx] = []
                        val_threshold_memberships[dataset_idx].append(val_threshold_key)
    
    print(f"Unified validation set: {len(all_val_indices)} unique samples across all thresholds")
    
    # Group by individual for training
    train_dataset_indices = []
    individual_to_class = {}
    dataset_info = {}
    
    for class_idx, individual_id in enumerate(individuals):
        # Get this individual's data
        ind_data = df[df['id'] == individual_id]
        
        # Get validation indices for training threshold to exclude from training
        training_threshold_key = f'threshold_{threshold_value:.1f}'
        if training_threshold_key not in validation_config['validation_indices'][individual_id]:
            raise ValueError(f"No validation indices found for {training_threshold_key} for individual {individual_id}")
        
        threshold_val_data = validation_config['validation_indices'][individual_id][training_threshold_key]
        frozen_val_indices = threshold_val_data['indices']
        
        # Filter training samples by quality threshold (excluding validation samples)
        available_for_training = ind_data[~ind_data.index.isin(frozen_val_indices)]
        eligible_training = available_for_training[available_for_training['pelage_score'] >= threshold_value]
        
        if len(eligible_training) < sample_size:
            raise ValueError(
                f"INSUFFICIENT TRAINING SAMPLES: Individual {individual_id} has only {len(eligible_training)} samples "
                f"with pelage_score ≥ {threshold_value:.1f}, but need {sample_size}"
            )
        
        # Sample training data randomly from eligible samples
        if len(eligible_training) > sample_size:
            train_samples = eligible_training.sample(n=sample_size, random_state=seed)
        else:
            train_samples = eligible_training
        
        train_indices_mapped = train_samples['index'].tolist()
        train_dataset_indices.extend(train_indices_mapped)
        
        individual_to_class[individual_id] = class_idx
        
        # Store dataset info
        dataset_info[individual_id] = {
            'total_available': len(ind_data),
            'available_for_training': len(available_for_training),
            'eligible_for_training': len(eligible_training),
            'training_samples_used': len(train_samples),
            'training_threshold': threshold_value
        }
        
        print(f"  {individual_id}: {len(train_samples)} train (from {len(eligible_training)} eligible at ≥{threshold_value:.1f})")
    
    # Create subset datasets
    train_subset = dataset.select(train_dataset_indices)
    val_indices_list = list(all_val_indices)
    val_subset = dataset.select(val_indices_list)
    
    # Remap val_threshold_memberships to use new validation dataset indices
    # val_indices_list[new_idx] = original_dataset_idx
    remapped_val_threshold_memberships = {}
    for new_idx, original_idx in enumerate(val_indices_list):
        if original_idx in val_threshold_memberships:
            remapped_val_threshold_memberships[new_idx] = val_threshold_memberships[original_idx]
    
    print(f"Final datasets: {len(train_subset)} train, {len(val_subset)} validation")
    print(f"Remapped {len(remapped_val_threshold_memberships)} validation threshold memberships")
    
    return train_subset, val_subset, individual_to_class, dataset_info, remapped_val_threshold_memberships


def create_dinov3_transform():
    """Create DINOv3-specific transform pipeline for reidentification images"""
    print("DINOv3 transform: resize to 224x224 + normalize (using reidentification config images)")
    
    return T.Compose([
        T.Resize(size=(224, 224), interpolation=Image.LANCZOS),
        T.ToTensor(), 
        T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # ImageNet stats for DINOv3
    ])


def calculate_bin_metrics_from_scores(predictions, labels, pelage_scores):
    """Calculate accuracy metrics by quality bin from pelage scores"""
    # Define quality bins
    quality_bins = [
        (0.8, 1.0, '[0.8,1.0]'),
        (0.6, 0.8, '[0.6,0.8)'), 
        (0.4, 0.6, '[0.4,0.6)'),
        (0.2, 0.4, '[0.2,0.4)'),
        (0.0, 0.2, '[0.0,0.2)')
    ]
    
    bin_metrics = {}
    
    for min_score, max_score, bin_name in quality_bins:
        # Find samples in this bin
        if max_score == 1.0:  # Inclusive upper bound for highest bin
            bin_mask = (pelage_scores >= min_score) & (pelage_scores <= max_score)
        else:  # Exclusive upper bound for other bins
            bin_mask = (pelage_scores >= min_score) & (pelage_scores < max_score)
        
        bin_indices = np.where(bin_mask)[0]
        
        if len(bin_indices) > 0:
            bin_preds = predictions[bin_indices]
            bin_labels = labels[bin_indices]
            bin_acc = (bin_preds == bin_labels).mean()
            
            bin_metrics[bin_name] = {
                'accuracy': float(bin_acc),
                'count': len(bin_indices),
                'sample_indices': bin_indices.tolist()
            }
        else:
            bin_metrics[bin_name] = {
                'accuracy': 0.0,
                'count': 0,
                'sample_indices': []
            }
    
    return bin_metrics


def validate_all_thresholds(model, val_loader, device, debug=False):
    """Single validation pass that computes metrics for all threshold levels"""
    from sklearn.metrics import f1_score
    
    model.eval()
    
    # Collect predictions and labels with threshold memberships
    all_preds = []
    all_labels = []
    all_pelage_scores = []
    all_threshold_memberships = []
    
    with torch.no_grad():
        for batch_idx, batch in enumerate(val_loader):
            images, labels, pelage_scores, threshold_memberships = batch
            images = images.to(device)
            outputs = model(images)
            preds = outputs.argmax(dim=1).cpu().numpy()
            
            all_preds.extend(preds)
            all_labels.extend(labels.numpy())
            all_pelage_scores.extend(pelage_scores.numpy())
            all_threshold_memberships.extend(threshold_memberships)
            
            # Debug: Print first batch's threshold memberships and validate data
            if batch_idx == 0 and debug:
                print(f"DEBUG: First batch threshold_memberships sample: {threshold_memberships[0] if len(threshold_memberships) > 0 else 'EMPTY'}")
                print(f"DEBUG: Val batch labels range: [{labels.min()}, {labels.max()}]")
                print(f"DEBUG: Val batch predictions range: [{preds.min()}, {preds.max()}]")
                print(f"DEBUG: Val batch size: {len(labels)}, threshold_memberships count: {len(threshold_memberships)}")
    
    # Convert to numpy arrays
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    all_pelage_scores = np.array(all_pelage_scores)
    
    if debug:
        print(f"DEBUG: Total validation samples: {len(all_preds)}")
        print(f"DEBUG: Validation class distribution: {np.bincount(all_labels)}")
        print(f"DEBUG: Prediction class distribution: {np.bincount(all_preds)}")
        print(f"DEBUG: Threshold memberships count: {len(all_threshold_memberships)}")
        
        # Check threshold membership statistics
        threshold_counts = {}
        for memberships in all_threshold_memberships:
            for threshold in memberships:
                threshold_counts[threshold] = threshold_counts.get(threshold, 0) + 1
        print(f"DEBUG: Threshold membership counts: {threshold_counts}")
    
    # Compute metrics for each threshold
    threshold_metrics = {}
    for threshold_key in ['threshold_0.8', 'threshold_0.6', 'threshold_0.4', 'threshold_0.2', 'threshold_0.0']:
        # Find samples belonging to this threshold
        threshold_indices = [i for i, memberships in enumerate(all_threshold_memberships) 
                            if threshold_key in memberships]
        
        if threshold_indices:
            threshold_indices = np.array(threshold_indices)
            threshold_preds = all_preds[threshold_indices]
            threshold_labels = all_labels[threshold_indices]
            threshold_pelage = all_pelage_scores[threshold_indices]
            
            # Debug: Check if we have valid predictions and labels
            if len(threshold_preds) == 0 or len(threshold_labels) == 0:
                if debug:
                    print(f"DEBUG: {threshold_key} has empty predictions or labels")
                accuracy = 0.0
                f1_macro = 0.0
            else:
                # Compute overall metrics
                accuracy = (threshold_preds == threshold_labels).mean()
                f1_macro = f1_score(threshold_labels, threshold_preds, average='macro', zero_division=0)
                if debug:
                    print(f"DEBUG: {threshold_key} - {len(threshold_indices)} samples, accuracy: {accuracy:.4f}")
            
            # Compute bin-specific metrics
            bin_metrics = calculate_bin_metrics_from_scores(
                threshold_preds, threshold_labels, threshold_pelage
            )
            
            threshold_metrics[threshold_key] = {
                'accuracy': float(accuracy),
                'f1_macro': float(f1_macro),
                'sample_count': len(threshold_indices),
                'bin_metrics': bin_metrics
            }
        else:
            # No samples for this threshold
            threshold_metrics[threshold_key] = {
                'accuracy': 0.0,
                'f1_macro': 0.0,
                'sample_count': 0,
                'bin_metrics': {}
            }
    
    return threshold_metrics


def train_single_config(sample_size: int, threshold_approach: str, seed: int, args: argparse.Namespace, dataset, config) -> dict:
    """Train one configuration and return results"""
    
    # Set seed
    set_all_seeds(seed)
    
    # Create output filename
    filename = f"samples={sample_size}_threshold={threshold_approach}_seed={seed}.json"
    output_path = os.path.join(args.output_dir, filename)
    
    # Check if should skip
    if check_result_exists(output_path) and not args.overwrite:
        print(f"Skipping existing result: {filename}")
        return None
    
    print(f"Training: samples={sample_size}, threshold={threshold_approach}, seed={seed}")
    
    # Dataset and config are passed as parameters (loaded once in main)
    
    # Check if we have validation indices
    if 'validation_indices' not in config:
        print("Error: No validation indices found. Please run 00_count_individuals.py first.")
        return None
    
    # Check if validation strategy is cumulative
    if 'validation_strategy' not in config or config['validation_strategy'].get('type') != 'cumulative_by_threshold':
        print("Error: Expected cumulative validation strategy. Please re-run 00_count_individuals.py.")
        return None
    
    # Find ALL individuals feasible for this sample_size/threshold combination
    # Use only the valid individuals that can support max_examples_per_class
    threshold_value = float(threshold_approach.split('_')[1])
    threshold_key = f'threshold_{threshold_value:.1f}'
    
    # Get the list of valid individuals from config (already filtered for max_examples_per_class)
    valid_individuals = config.get('valid_individuals', [])
    
    # Use only valid individuals - they are already filtered to support max_examples_per_class
    # We don't need to double-check compatible_training_sizes since valid_individuals are pre-filtered
    feasible_individuals = []
    for ind_id in valid_individuals:
        compat = config['validation_compatibility'][ind_id]
        if threshold_key in compat['threshold_compatibility']:
            feasible_individuals.append(ind_id)
    
    if not feasible_individuals:
        print(f"No feasible individuals for {sample_size} samples at threshold ≥{threshold_value:.1f}")
        return None
    
    max_examples_per_class = config.get('max_examples_per_class', 'unknown')
    print(f"Using {len(feasible_individuals)} feasible individuals (from {len(valid_individuals)} valid for max_examples_per_class={max_examples_per_class}) at threshold ≥{threshold_value:.1f}: {', '.join(feasible_individuals)}")
    
    # Show individual details
    for ind_id in feasible_individuals:
        pelage_score = config['individual_pelage_scores'][ind_id]
        compat = config['validation_compatibility'][ind_id]
        threshold_compat = compat['threshold_compatibility'][threshold_key]
        max_train = threshold_compat['max_training_size']
        eligible = threshold_compat['eligible_samples']
        val_used = threshold_compat['validation_samples']
        
        print(f"  {ind_id}: pelage_score={pelage_score:.3f}, {eligible} eligible, {val_used} val, max train: {max_train}")
    
    # Create quality threshold dataset splits
    try:
        ind_train_dataset, ind_val_dataset, individual_to_class, dataset_info, val_threshold_memberships = create_quality_threshold_dataset(
            dataset, feasible_individuals, sample_size, threshold_approach, seed, config
        )
    except ValueError as e:
        print(f"FATAL ERROR: {e}")
        raise e
    
    num_classes = len(feasible_individuals)
    print(f"Multi-class problem: {num_classes} individuals (classes)")
    
    print(f"Train samples: {len(ind_train_dataset)}")
    print(f"Val samples: {len(ind_val_dataset)}")
    
    # Create transforms for reidentification images
    batch_size = 16
    transform = create_dinov3_transform()
    
    # Create custom dataloaders for reidentification dataset
    from torch.utils.data import DataLoader, Dataset as TorchDataset
    
    class ReidentificationDataset(TorchDataset):
        def __init__(self, dataset, transform, individual_to_class, val_threshold_memberships=None):
            """
            val_threshold_memberships: dict mapping sample_idx to list of thresholds it belongs to
            e.g., {0: ['threshold_0.0', 'threshold_0.2'], 1: ['threshold_0.0'], ...}
            """
            self.dataset = dataset
            self.transform = transform
            self.individual_to_class = individual_to_class
            self.val_threshold_memberships = val_threshold_memberships or {}
            
        def __len__(self):
            return len(self.dataset)
            
        def __getitem__(self, idx):
            sample = self.dataset[idx]
            
            # Use the image from reidentification config
            image = sample['image']
            
            # Apply transforms
            image = self.transform(image)
            
            # Get class label and pelage score
            individual_id = sample['id']
            class_label = self.individual_to_class[individual_id]
            pelage_score = sample['pelage_score']
            
            # Include which validation thresholds this sample belongs to
            threshold_memberships = self.val_threshold_memberships.get(idx, [])
            
            return image, class_label, pelage_score, threshold_memberships
    
    # Validate that all individuals in validation set are in the class mapping
    val_individuals = set()
    for sample in ind_val_dataset:
        val_individuals.add(sample['id'])
    
    missing_individuals = val_individuals - set(individual_to_class.keys())
    if missing_individuals:
        raise ValueError(f"Validation set contains individuals not in class mapping: {missing_individuals}")
    
    print(f"✓ Class mapping validation passed: all {len(val_individuals)} validation individuals are in the mapping")
    
    train_dataset_torch = ReidentificationDataset(ind_train_dataset, transform, individual_to_class)
    val_dataset_torch = ReidentificationDataset(ind_val_dataset, transform, individual_to_class, val_threshold_memberships)
    
    train_loader = DataLoader(train_dataset_torch, batch_size=batch_size, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_dataset_torch, batch_size=batch_size, shuffle=False, num_workers=0)
    
    # Create model (modify for multi-class)
    device = "cuda" if args.device == "gpu" else "cpu"
    model = create_model(device=device, num_classes=num_classes)
    
    print(f"Using device: {device}")
    print(f"Model classes: {num_classes}")
    
    # Create trainer using shared MultiClassTrainer
    trainer = MultiClassTrainer(
        model=model,
        device=device,
        learning_rate=0.001,
        weight_decay=0.01
    )
    
    # Train
    start_time = time.time()
    epochs = 50  # Reasonable for multi-class with limited samples
    
    # Enhanced training with cross-threshold validation
    for epoch in range(epochs):
        # Training
        train_loss, train_acc = trainer.train_epoch(train_loader)
        
        # Add validation checks for first epoch
        if epoch == 0:
            print(f"Validation checks - Model has {num_classes} classes")
            # Check a sample batch to ensure data integrity
            for batch_idx, batch in enumerate(train_loader):
                images, labels, _, _ = batch
                assert torch.all(labels >= 0) and torch.all(labels < num_classes), f"Invalid train labels: min={labels.min()}, max={labels.max()}, expected range [0, {num_classes-1}]"
                outputs = model(images.to(device))
                assert outputs.shape == (len(labels), num_classes), f"Model output shape {outputs.shape} != expected ({len(labels)}, {num_classes})"
                if batch_idx == 0:  # Only check first batch
                    print(f"✓ Data validation passed: labels in [0,{num_classes-1}], model outputs shape {outputs.shape}")
                break
        
        # Validation across all threshold levels
        val_metrics_all_thresholds = validate_all_thresholds(model, val_loader, device, epoch == 0)
        
        # Use the training threshold's validation metrics for primary reporting
        training_threshold_key = f'threshold_{threshold_value:.1f}'
        primary_val_metrics = val_metrics_all_thresholds.get(training_threshold_key, {
            'accuracy': 0.0, 'f1_macro': 0.0, 'sample_count': 0, 'bin_metrics': {}
        })
        
        # Save history
        trainer.train_history.append({
            'epoch': epoch + 1,
            'loss': train_loss,
            'accuracy': train_acc
        })
        
        trainer.val_history.append({
            'epoch': epoch + 1,
            'training_threshold_validation': primary_val_metrics,
            'all_threshold_validation': val_metrics_all_thresholds
        })
        
        # Print progress
        if True:  # verbose
            primary_acc = primary_val_metrics['accuracy']
            msg = f"Epoch {epoch+1:2d}/{epochs}: Train Acc={train_acc:.4f}, Val Acc@{threshold_value:.1f}={primary_acc:.4f}"
            
            # Add cross-threshold validation summary
            threshold_accs = []
            for thresh_key in ['threshold_0.8', 'threshold_0.6', 'threshold_0.4', 'threshold_0.2', 'threshold_0.0']:
                if thresh_key in val_metrics_all_thresholds:
                    thresh_acc = val_metrics_all_thresholds[thresh_key]['accuracy']
                    thresh_count = val_metrics_all_thresholds[thresh_key]['sample_count']
                    thresh_val = float(thresh_key.split('_')[1])
                    threshold_accs.append(f"{thresh_val:.1f}:{thresh_acc:.3f}({thresh_count})")
            
            if threshold_accs:
                msg += f", All thresholds: {', '.join(threshold_accs)}"
            
            print(msg)
    
    training_time = time.time() - start_time
    
    # Final evaluation across all thresholds
    final_val_metrics_all_thresholds = validate_all_thresholds(model, val_loader, device)
    
    # Get final metrics for the training threshold
    training_threshold_key = f'threshold_{threshold_value:.1f}'
    final_primary_metrics = final_val_metrics_all_thresholds.get(training_threshold_key, {
        'accuracy': 0.0, 'f1_macro': 0.0, 'sample_count': 0, 'bin_metrics': {}
    })
    
    results = {
        'epochs_trained': epochs,
        'training_threshold': threshold_value,
        'final_validation_by_threshold': final_val_metrics_all_thresholds,
        'final_training_threshold_validation': final_primary_metrics,
        'best_epoch_by_threshold': {}  # Could track best epoch per threshold if needed
    }
    
    # Prepare comprehensive results
    final_results = {
        'job_idx': args.idx,
        'sample_size': sample_size,
        'threshold_approach': threshold_approach,
        'threshold_value': threshold_value,
        'seed': seed,
        'num_classes': num_classes,
        'num_individuals': len(feasible_individuals),
        'individual_ids': feasible_individuals,
        'individual_to_class': individual_to_class,
        'individual_scores': {ind_id: config['individual_pelage_scores'][ind_id] for ind_id in feasible_individuals},
        'dataset_info': dataset_info,
        'validation_threshold_memberships': {int(k): v for k, v in val_threshold_memberships.items()},
        'dataset_stats': {
            'total_samples_used': len(ind_train_dataset) + len(ind_val_dataset),
            'train_samples': len(ind_train_dataset),
            'val_samples': len(ind_val_dataset),
            'samples_per_individual': sample_size,
            'threshold_used': threshold_value
        },
        'training_time': training_time,
        'performance': results,
        'train_history': trainer.train_history,
        'val_history': trainer.val_history,
        'experimental_params': {
            'threshold_approach': threshold_approach,
            'approach_details': f'Quality threshold approach: train on samples with pelage_score ≥ {threshold_value:.1f}, validate on all five cumulative threshold levels',
            'dataset_config': 'reidentification',
            'quality_bins': '[0.0,0.2), [0.2,0.4), [0.4,0.6), [0.6,0.8), [0.8,1.0]',
            'validation_strategy': 'cross_threshold_unified_validation',
            'validation_thresholds': ['0.8', '0.6', '0.4', '0.2', '0.0'],
            'batch_size': batch_size,
            'epochs': epochs,
            'learning_rate': 0.001,
            'weight_decay': 0.01
        }
    }
    
    # Save results
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(final_results, f, indent=2)
    
    print(f"✓ Saved results to: {filename}")
    print(f"  Final validation accuracy: {results['final_val_accuracy']:.4f}")
    
    # Show quality bin-specific performance if available
    if final_bin_metrics:
        print("  Final accuracy by quality bin:")
        for bin_name in ['[0.0,0.2)', '[0.2,0.4)', '[0.4,0.6)', '[0.6,0.8)', '[0.8,1.0]']:
            if bin_name in final_bin_metrics and final_bin_metrics[bin_name]['count'] > 0:
                acc = final_bin_metrics[bin_name]['accuracy']
                count = final_bin_metrics[bin_name]['count']
                print(f"    {bin_name}: {acc:.4f} (n={count})")
            elif bin_name in final_bin_metrics:
                print(f"    {bin_name}: no samples")
    
    print(f"  Training time: {training_time/60:.1f} minutes")
    
    return final_results


def main():
    parser = argparse.ArgumentParser(description='Individual ID classification sweep')
    parser.add_argument('--idx', type=int, required=True, 
                       help='Job index (0-23)')
    parser.add_argument('--overwrite', action='store_true',
                       help='Overwrite existing results')
    parser.add_argument('--output_dir', type=str,
                       default='individual_id/results',
                       help='Output directory for results')
    parser.add_argument('--device', type=str, choices=['gpu', 'cpu'],
                       default='gpu', help='Device to use for training')
    
    args = parser.parse_args()
    
    print("=" * 80)
    print(f"Individual ID Classification - Job {args.idx}")
    print("=" * 80)
    
    # Load dataset and config once for all configurations
    print("Loading dataset once for all configurations...")
    dataset = load_reidentification_dataset()
    config = load_feasibility_config()
    
    if not config:
        print("Failed to load feasibility config")
        return
    
    # Show distribution info
    sample_sizes = config.get('training_sizes', [1, 2, 4, 8, 16, 32, 64])
    thresholds = ['threshold_0.0', 'threshold_0.2', 'threshold_0.4', 'threshold_0.6', 'threshold_0.8']
    seeds = [0, 1, 2, 3, 4, 5, 6, 7]
    total_combinations = len(sample_sizes) * len(thresholds) * len(seeds)
    
    configs_per_job = total_combinations // 24
    remainder = total_combinations % 24
    
    print(f"Total experiment combinations: {total_combinations}")
    print(f"Training sizes: {sample_sizes}")
    print(f"Distribution: {remainder} jobs get {configs_per_job + 1} configs, {24 - remainder} jobs get {configs_per_job} configs")
    
    if args.idx < remainder:
        expected_configs = configs_per_job + 1
    else:
        expected_configs = configs_per_job
    print(f"Job {args.idx} expected to process: {expected_configs} configurations")
    
    # Get combinations for this job
    combinations = get_job_combinations(args.idx)
    
    if not combinations:
        print(f"No combinations assigned to job {args.idx}")
        return
    
    print(f"Actually processing {len(combinations)} configurations:")
    for sample_size, threshold, seed in combinations:
        print(f"  Samples: {sample_size}, Threshold: {threshold}, Seed: {seed}")
    
    # Train each combination using the shared dataset and config
    results_summary = []
    for i, (sample_size, threshold, seed) in enumerate(combinations):
        print(f"\n--- Configuration {i+1}/{len(combinations)} ---")
        try:
            result = train_single_config(sample_size, threshold, seed, args, dataset, config)
            if result:
                results_summary.append(result)
        except Exception as e:
            print(f"Error training samples={sample_size}, threshold={threshold}, seed={seed}: {e}")
            continue
    
    print(f"\n" + "=" * 80)
    print(f"Job {args.idx} completed!")
    print(f"Successfully processed {len(results_summary)} configurations")
    
    if results_summary:
        avg_acc = sum(r['performance']['final_val_accuracy'] for r in results_summary) / len(results_summary)
        best_acc = max(r['performance']['final_val_accuracy'] for r in results_summary)
        avg_f1 = sum(r['performance']['final_val_f1_macro'] for r in results_summary) / len(results_summary)
        best_f1 = max(r['performance']['final_val_f1_macro'] for r in results_summary)
        print(f"Average final validation accuracy: {avg_acc:.4f}")
        print(f"Best final validation accuracy: {best_acc:.4f}")
        print(f"Average final validation F1 (macro): {avg_f1:.4f}")
        print(f"Best final validation F1 (macro): {best_f1:.4f}")
        print(f"Results saved to: {args.output_dir}")

if __name__ == "__main__":
    main()