#!/usr/bin/env python3
"""
Script 01: Individual ID Sweep (Crops-Masks Config)
Multi-class classification experiment with varying samples per individual.
Uses crops-masks dataset configuration with detection filtering and temporal splits.
"""

import sys
import os
import argparse
import time
import json
import csv
import torch
import numpy as np
from pathlib import Path
from sklearn.metrics import confusion_matrix

# Control parallelism to prevent OOM issues
os.environ["TOKENIZERS_PARALLELISM"] = "false"  # Disable tokenizer parallelism
os.environ["HF_DATASETS_OFFLINE"] = "1"  # Use cached data only

# Assume script is run from wolverines root directory
sys.path.append('.')

from utils.dataset import set_all_seeds
from utils.models import create_model
from utils.training import check_result_exists, MultiClassTrainer
from datasets import load_dataset
import torchvision.transforms as T
from PIL import Image

# Configure datasets library to use single process
import datasets
datasets.config.NUM_PROC = 1


def load_feasibility_config():
    """Load the feasibility configuration from script 00"""
    config_path = 'individual_id/results/feasible_individuals.json'
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: {config_path} not found. Please run 00_count_individuals.py first.")
        return None


def get_job_combinations(job_idx: int, max_jobs: int = 24) -> list:
    """Map job index to list of (sample_size, threshold, seed) tuples"""
    
    # Load dynamic parameters from feasibility config
    config = load_feasibility_config()
    if config is None:
        return []
    
    # Get training sizes from config (generated by script 00)
    sample_sizes = config.get('training_sizes', [1, 2, 4, 8, 16, 32, 64])
    thresholds = config.get('thresholds', [0, 0.25, 0.5, 0.75])  # 4 thresholds
    seeds = [0, 1, 2, 3, 4, 5, 6, 7]  # 8 seeds
    
    # Generate all combinations: len(sample_sizes) × 4 thresholds × 8 seeds
    all_combinations = []
    for sample_size in sample_sizes:
        for threshold in thresholds:
            for seed in seeds:
                all_combinations.append((sample_size, threshold, seed))
    
    total_combinations = len(all_combinations)
    
    # Handle case where job_idx exceeds available jobs or no combinations
    if job_idx >= max_jobs or total_combinations == 0:
        return []
    
    # Dynamic job distribution: handle any number of combinations
    configs_per_job = total_combinations // max_jobs
    remainder = total_combinations % max_jobs
    
    # Jobs 0 to (remainder-1) get one extra config to handle remainder
    if job_idx < remainder:
        start_idx = job_idx * (configs_per_job + 1)
        end_idx = start_idx + configs_per_job + 1
    else:
        start_idx = remainder * (configs_per_job + 1) + (job_idx - remainder) * configs_per_job
        end_idx = start_idx + configs_per_job
    
    # Handle case where this job has no work (total_combinations < max_jobs)
    if start_idx >= total_combinations:
        return []
    
    # Ensure we don't exceed the total combinations
    end_idx = min(end_idx, total_combinations)
    
    return all_combinations[start_idx:end_idx]


def load_reidentification_dataset():
    """Load the wolverines dataset with reidentification configuration"""
    print("Loading wolverines dataset (reidentification config)...")
    dataset = load_dataset("kdoherty/wolverines", "reidentification", split="train")
    print(f"Loaded {len(dataset)} samples from reidentification config")
    return dataset


def create_temporal_threshold_dataset(dataset, individuals, sample_size, threshold_value, seed, config):
    """Create temporal validation dataset with quality threshold filtering for training"""
    import random
    
    random.seed(seed)
    np.random.seed(seed)
    
    print(f"Creating temporal validation dataset: {sample_size} samples per class, training threshold≥{threshold_value:.2f}")
    
    # Convert dataset to DataFrame for easier processing
    data_list = []
    for i, sample in enumerate(dataset):
        data_list.append({
            'index': i,
            'id': sample['id'],
            'ymdh': sample['ymdh'],
            'pelage_score': sample['pelage_score']
        })
    
    import pandas as pd
    df = pd.DataFrame(data_list)
    
    # Build validation set using fixed temporal split
    all_val_indices = []
    for individual_id in individuals:
        val_indices = config['validation_indices'][individual_id]['indices']
        all_val_indices.extend(val_indices)
    
    print(f"Validation set: {len(all_val_indices)} samples (fixed temporal split)")
    
    # Group by individual for training
    train_dataset_indices = []
    individual_to_class = {}
    dataset_info = {}
    
    for class_idx, individual_id in enumerate(individuals):
        # Get this individual's data
        ind_data = df[df['id'] == individual_id]
        
        # Get validation indices (same for all thresholds now)
        val_indices = config['validation_indices'][individual_id]['indices']
        
        # Filter training samples by quality threshold (excluding validation samples)
        available_for_training = ind_data[~ind_data.index.isin(val_indices)]
        eligible_training = available_for_training[available_for_training['pelage_score'] >= threshold_value]
        
        if len(eligible_training) < sample_size:
            raise ValueError(
                f"INSUFFICIENT TRAINING SAMPLES: Individual {individual_id} has only {len(eligible_training)} samples "
                f"with pelage_score ≥ {threshold_value:.2f}, but need {sample_size}"
            )
        
        # Sample training data randomly from eligible samples
        if len(eligible_training) > sample_size:
            train_samples = eligible_training.sample(n=sample_size, random_state=seed)
        else:
            train_samples = eligible_training
        
        train_indices_mapped = train_samples['index'].tolist()
        train_dataset_indices.extend(train_indices_mapped)
        
        individual_to_class[individual_id] = class_idx
        
        # Store dataset info
        dataset_info[individual_id] = {
            'total_available': len(ind_data),
            'available_for_training': len(available_for_training),
            'eligible_for_training': len(eligible_training),
            'training_samples_used': len(train_samples),
            'training_threshold': threshold_value,
            'validation_samples': len(val_indices)
        }
        
        print(f"  {individual_id}: {len(train_samples)} train (from {len(eligible_training)} eligible at ≥{threshold_value:.2f}), {len(val_indices)} val")
    
    # Create subset datasets
    train_subset = dataset.select(train_dataset_indices)
    val_subset = dataset.select(all_val_indices)
    
    print(f"Final datasets: {len(train_subset)} train, {len(val_subset)} validation")
    
    return train_subset, val_subset, individual_to_class, dataset_info


def create_dinov3_transform():
    """Create DINOv3-specific transform pipeline for reidentification images"""
    print("DINOv3 transform: resize to 224x224 + normalize (using reidentification config images)")
    
    return T.Compose([
        T.Resize(size=(224, 224), interpolation=Image.LANCZOS),
        T.ToTensor(), 
        T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # ImageNet stats for DINOv3
    ])


def calculate_bin_metrics_from_scores(predictions, labels, pelage_scores):
    """Calculate accuracy and macro F1 metrics by quality bin from pelage scores"""
    from sklearn.metrics import f1_score
    
    # Define quality bins - new 4-bin structure
    quality_bins = [
        (0.75, 1.0, '[0.75,1.0]'),   # Highest quality
        (0.50, 0.75, '[0.5,0.75)'),  # High quality
        (0.25, 0.50, '[0.25,0.5)'),  # Medium quality
        (0.00, 0.25, '[0,0.25)')     # Low quality
    ]
    
    bin_metrics = {}
    
    for min_score, max_score, bin_name in quality_bins:
        # Find samples in this bin
        if bin_name == '[0.75,1.0]':  # Inclusive upper bound for highest bin
            bin_mask = (pelage_scores >= min_score) & (pelage_scores <= max_score)
        else:  # Exclusive upper bound for other bins
            bin_mask = (pelage_scores >= min_score) & (pelage_scores < max_score)
        
        bin_indices = np.where(bin_mask)[0]
        
        if len(bin_indices) > 0:
            bin_preds = predictions[bin_indices]
            bin_labels = labels[bin_indices]
            bin_acc = (bin_preds == bin_labels).mean()
            bin_f1_macro = f1_score(bin_labels, bin_preds, average='macro', zero_division=0)
            
            bin_metrics[bin_name] = {
                'accuracy': float(bin_acc),
                'f1_macro': float(bin_f1_macro),
                'count': len(bin_indices),
                'sample_indices': bin_indices.tolist()
            }
        else:
            bin_metrics[bin_name] = {
                'accuracy': 0.0,
                'f1_macro': 0.0,
                'count': 0,
                'sample_indices': []
            }
    
    return bin_metrics


def validate_with_bin_metrics(model, val_loader, device, debug=False):
    """Single validation pass that computes overall and bin-specific metrics with F1 as primary metric"""
    from sklearn.metrics import f1_score
    
    model.eval()
    
    # Collect predictions, labels, and pelage scores
    all_preds = []
    all_labels = []
    all_pelage_scores = []
    
    with torch.no_grad():
        for batch_idx, batch in enumerate(val_loader):
            images, labels, pelage_scores = batch
            images = images.to(device)
            outputs = model(images)
            preds = outputs.argmax(dim=1).cpu().numpy()
            
            all_preds.extend(preds)
            all_labels.extend(labels.numpy())
            all_pelage_scores.extend(pelage_scores.numpy())
            
            # Debug: Print first batch info
            if batch_idx == 0 and debug:
                print(f"DEBUG: Val batch labels range: [{labels.min()}, {labels.max()}]")
                print(f"DEBUG: Val batch predictions range: [{preds.min()}, {preds.max()}]")
                print(f"DEBUG: Val batch size: {len(labels)}")
    
    # Convert to numpy arrays
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    all_pelage_scores = np.array(all_pelage_scores)
    
    if debug:
        print(f"DEBUG: Total validation samples: {len(all_preds)}")
        print(f"DEBUG: Validation class distribution: {np.bincount(all_labels)}")
        print(f"DEBUG: Prediction class distribution: {np.bincount(all_preds)}")
    
    # Compute overall metrics
    overall_accuracy = (all_preds == all_labels).mean()
    overall_f1 = f1_score(all_labels, all_preds, average='macro', zero_division=0)
    
    # Compute bin-specific metrics
    bin_metrics = calculate_bin_metrics_from_scores(all_preds, all_labels, all_pelage_scores)
    
    if debug:
        print(f"DEBUG: Overall accuracy: {overall_accuracy:.4f}, F1: {overall_f1:.4f}")
        for bin_name, metrics in bin_metrics.items():
            if metrics['count'] > 0:
                print(f"DEBUG: {bin_name}: acc={metrics['accuracy']:.4f}, f1={metrics['f1_macro']:.4f} (n={metrics['count']})")
    
    return {
        'overall_accuracy': float(overall_accuracy),
        'overall_f1': float(overall_f1),
        'sample_count': len(all_preds),
        'bin_metrics': bin_metrics
    }


def train_single_config(sample_size: int, threshold_approach: str, seed: int, args: argparse.Namespace, dataset, config) -> dict:
    """Train one configuration and return results"""
    
    # Set seed
    set_all_seeds(seed)
    
    # Create output filename
    filename = f"samples={sample_size}_threshold={threshold_approach:.2f}_seed={seed}.csv"
    output_path = os.path.join(args.output_dir, filename)
    
    # Check if should skip
    if check_result_exists(output_path) and not args.overwrite:
        print(f"Skipping existing result: {filename}")
        return None
    
    print(f"Training: samples={sample_size}, threshold={threshold_approach}, seed={seed}")
    
    # Dataset and config are passed as parameters (loaded once in main)
    
    # Check if we have validation indices
    if 'validation_indices' not in config:
        print("Error: No validation indices found. Please run 00_count_individuals.py first.")
        return None
    
    # Check if validation strategy is temporal
    expected_strategies = ['temporal_last_ymdh', 'temporal_greedy_bins']
    if 'validation_strategy' not in config or config['validation_strategy'].get('type') not in expected_strategies:
        print("Error: Expected temporal validation strategy. Please re-run 00_count_individuals.py.")
        return None
    
    # Find individuals feasible for this sample_size/threshold combination
    threshold_value = threshold_approach  # Now a float, not a string
    threshold_key = f'threshold_{threshold_value:.2f}'
    
    # Get the list of valid individuals from config
    valid_individuals = config.get('valid_individuals', [])
    
    # Check which individuals can support this training size at this threshold
    feasible_individuals = []
    for ind_id in valid_individuals:
        training_compat = config['training_compatibility'][ind_id]
        threshold_compat = training_compat['threshold_compatibility'].get(threshold_key, {})
        compatible_sizes = threshold_compat.get('compatible_training_sizes', [])
        
        if sample_size in compatible_sizes:
            feasible_individuals.append(ind_id)
    
    if not feasible_individuals:
        print(f"No feasible individuals for {sample_size} samples at threshold ≥{threshold_value:.1f}")
        return None
    
    max_examples_per_class = config.get('max_examples_per_class', 'unknown')
    print(f"Using {len(feasible_individuals)} feasible individuals (from {len(valid_individuals)} valid) at threshold ≥{threshold_value:.2f}: {', '.join(feasible_individuals)}")
    
    # Show individual details
    for ind_id in feasible_individuals:
        pelage_score = config['individual_pelage_scores'][ind_id]
        # Get validation count (same for all thresholds now)
        val_count = config['validation_indices'][ind_id]['count']
        print(f"  {ind_id}: pelage_score={pelage_score:.3f}, {val_count} validation samples")
    
    # Create temporal threshold dataset splits
    try:
        ind_train_dataset, ind_val_dataset, individual_to_class, dataset_info = create_temporal_threshold_dataset(
            dataset, feasible_individuals, sample_size, threshold_value, seed, config
        )
    except ValueError as e:
        print(f"FATAL ERROR: {e}")
        raise e
    
    num_classes = len(feasible_individuals)
    print(f"Multi-class problem: {num_classes} individuals (classes)")
    
    print(f"Train samples: {len(ind_train_dataset)}")
    print(f"Val samples: {len(ind_val_dataset)}")
    
    # Create transforms for reidentification images
    batch_size = 16
    transform = create_dinov3_transform()
    
    # Create custom dataloaders for reidentification dataset
    from torch.utils.data import DataLoader, Dataset as TorchDataset
    
    class ReidentificationDataset(TorchDataset):
        def __init__(self, dataset, transform, individual_to_class):
            self.dataset = dataset
            self.transform = transform
            self.individual_to_class = individual_to_class
            
        def __len__(self):
            return len(self.dataset)
            
        def __getitem__(self, idx):
            sample = self.dataset[idx]
            
            # Use the image from reidentification config
            image = sample['image']
            
            # Apply transforms
            image = self.transform(image)
            
            # Get class label and pelage score
            individual_id = sample['id']
            class_label = self.individual_to_class[individual_id]
            pelage_score = sample['pelage_score']
            
            return image, class_label, pelage_score
    
    # Validate that all individuals in validation set are in the class mapping
    val_individuals = set()
    for sample in ind_val_dataset:
        val_individuals.add(sample['id'])
    
    missing_individuals = val_individuals - set(individual_to_class.keys())
    if missing_individuals:
        raise ValueError(f"Validation set contains individuals not in class mapping: {missing_individuals}")
    
    print(f"✓ Class mapping validation passed: all {len(val_individuals)} validation individuals are in the mapping")
    
    train_dataset_torch = ReidentificationDataset(ind_train_dataset, transform, individual_to_class)
    val_dataset_torch = ReidentificationDataset(ind_val_dataset, transform, individual_to_class)
    
    # Custom collate function
    def custom_collate_fn(batch):
        images = torch.stack([item[0] for item in batch])
        labels = torch.tensor([item[1] for item in batch])
        pelage_scores = torch.tensor([item[2] for item in batch])
        return images, labels, pelage_scores
    
    train_loader = DataLoader(train_dataset_torch, batch_size=batch_size, shuffle=True, 
                             num_workers=0, collate_fn=custom_collate_fn)
    val_loader = DataLoader(val_dataset_torch, batch_size=batch_size, shuffle=False, 
                           num_workers=0, collate_fn=custom_collate_fn)
    
    # Create model (modify for multi-class)
    device = "cuda" if args.device == "gpu" else "cpu"
    model = create_model(device=device, num_classes=num_classes)
    
    print(f"Using device: {device}")
    print(f"Model classes: {num_classes}")
    
    # Create trainer using shared MultiClassTrainer
    trainer = MultiClassTrainer(
        model=model,
        device=device,
        learning_rate=0.001,
        weight_decay=0.01
    )
    
    # Train
    start_time = time.time()
    epochs = 50  # Reasonable for multi-class with limited samples
    
    # Enhanced training with cross-threshold validation
    for epoch in range(epochs):
        # Training
        train_loss, train_acc = trainer.train_epoch(train_loader)
        
        # Add validation checks for first epoch
        if epoch == 0:
            print(f"Validation checks - Model has {num_classes} classes")
            # Check a sample batch to ensure data integrity
            for batch_idx, batch in enumerate(train_loader):
                images, labels, _ = batch
                assert torch.all(labels >= 0) and torch.all(labels < num_classes), f"Invalid train labels: min={labels.min()}, max={labels.max()}, expected range [0, {num_classes-1}]"
                outputs = model(images.to(device))
                assert outputs.shape == (len(labels), num_classes), f"Model output shape {outputs.shape} != expected ({len(labels)}, {num_classes})"
                if batch_idx == 0:  # Only check first batch
                    print(f"✓ Data validation passed: labels in [0,{num_classes-1}], model outputs shape {outputs.shape}")
                break
        
        # Validation with bin-specific metrics
        val_metrics = validate_with_bin_metrics(model, val_loader, device, epoch == 0)
        
        # Save history
        trainer.train_history.append({
            'epoch': epoch + 1,
            'loss': train_loss,
            'accuracy': train_acc
        })
        
        trainer.val_history.append({
            'epoch': epoch + 1,
            'validation_metrics': val_metrics
        })
        
        # Print progress
        if True:  # verbose
            overall_f1 = val_metrics['overall_f1']
            overall_acc = val_metrics['overall_accuracy']
            msg = f"Epoch {epoch+1:2d}/{epochs}: Train Acc={train_acc:.4f}, Val F1={overall_f1:.4f}, Val Acc={overall_acc:.4f}"
            
            # Add bin-specific validation summary (F1 scores)
            bin_f1s = []
            for bin_name in ['[0.75,1.0]', '[0.5,0.75)', '[0.25,0.5)', '[0,0.25)']:
                if bin_name in val_metrics['bin_metrics'] and val_metrics['bin_metrics'][bin_name]['count'] > 0:
                    bin_f1 = val_metrics['bin_metrics'][bin_name]['f1_macro']
                    bin_count = val_metrics['bin_metrics'][bin_name]['count']
                    bin_f1s.append(f"{bin_name}:{bin_f1:.3f}({bin_count})")
            
            if bin_f1s:
                msg += f", Bin F1s: {', '.join(bin_f1s)}"
            
            print(msg)
    
    training_time = time.time() - start_time
    
    # Final evaluation with bin metrics
    final_val_metrics = validate_with_bin_metrics(model, val_loader, device)
    
    # Write CSV with epoch metrics
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', newline='') as csvfile:
        fieldnames = ['epoch', 'train_acc', 
                      'val_f1_overall', 'val_acc_overall',
                      'val_f1_bin_0.75_1.0', 'val_acc_bin_0.75_1.0',
                      'val_f1_bin_0.5_0.75', 'val_acc_bin_0.5_0.75', 
                      'val_f1_bin_0.25_0.5', 'val_acc_bin_0.25_0.5',
                      'val_f1_bin_0_0.25', 'val_acc_bin_0_0.25']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        
        # Write each epoch's metrics
        for i, (train_hist, val_hist) in enumerate(zip(trainer.train_history, trainer.val_history)):
            row = {
                'epoch': i + 1,
                'train_acc': train_hist['accuracy'],
                'val_f1_overall': val_hist['validation_metrics']['overall_f1'],
                'val_acc_overall': val_hist['validation_metrics']['overall_accuracy']
            }
            
            # Add bin-specific validation metrics (both F1 and accuracy)
            bin_metrics = val_hist['validation_metrics']['bin_metrics']
            for bin_name, f1_col, acc_col in [('[0.75,1.0]', 'val_f1_bin_0.75_1.0', 'val_acc_bin_0.75_1.0'), 
                                            ('[0.5,0.75)', 'val_f1_bin_0.5_0.75', 'val_acc_bin_0.5_0.75'),
                                            ('[0.25,0.5)', 'val_f1_bin_0.25_0.5', 'val_acc_bin_0.25_0.5'),
                                            ('[0,0.25)', 'val_f1_bin_0_0.25', 'val_acc_bin_0_0.25')]:
                if bin_name in bin_metrics and bin_metrics[bin_name]['count'] > 0:
                    row[f1_col] = bin_metrics[bin_name]['f1_macro']
                    row[acc_col] = bin_metrics[bin_name]['accuracy']
                else:
                    row[f1_col] = 0.0
                    row[acc_col] = 0.0
            
            writer.writerow(row)
    
    print(f"✓ Saved results to: {filename}")
    print(f"  Final validation F1: {final_val_metrics['overall_f1']:.4f}, Accuracy: {final_val_metrics['overall_accuracy']:.4f}")
    
    # Show quality bin-specific performance
    final_bin_metrics = final_val_metrics['bin_metrics']
    if final_bin_metrics:
        print("  Final F1 and accuracy by quality bin:")
        for bin_name in ['[0.75,1.0]', '[0.5,0.75)', '[0.25,0.5)', '[0,0.25)']:
            if bin_name in final_bin_metrics and final_bin_metrics[bin_name]['count'] > 0:
                f1 = final_bin_metrics[bin_name]['f1_macro']
                acc = final_bin_metrics[bin_name]['accuracy']
                count = final_bin_metrics[bin_name]['count']
                print(f"    {bin_name}: F1={f1:.4f}, Acc={acc:.4f} (n={count})")
            elif bin_name in final_bin_metrics:
                print(f"    {bin_name}: no samples")
    
    print(f"  Training time: {training_time/60:.1f} minutes")
    
    return filename  # Return filename for confirmation


def main():
    parser = argparse.ArgumentParser(description='Individual ID classification sweep')
    parser.add_argument('--idx', type=int, required=True, 
                       help='Job index (0-23)')
    parser.add_argument('--overwrite', action='store_true',
                       help='Overwrite existing results')
    parser.add_argument('--output_dir', type=str,
                       default='individual_id/results',
                       help='Output directory for results')
    parser.add_argument('--device', type=str, choices=['gpu', 'cpu'],
                       default='gpu', help='Device to use for training')
    
    args = parser.parse_args()
    
    print("=" * 80)
    print(f"Individual ID Classification - Job {args.idx}")
    print("=" * 80)
    
    # Load dataset and config once for all configurations
    print("Loading dataset once for all configurations...")
    dataset = load_reidentification_dataset()
    config = load_feasibility_config()
    
    if not config:
        print("Failed to load feasibility config")
        return
    
    # Show distribution info
    sample_sizes = config.get('training_sizes', [1, 2, 4, 8, 16, 32, 64])
    thresholds = config.get('thresholds', [0, 0.25, 0.5, 0.75])
    seeds = [0, 1, 2, 3, 4, 5, 6, 7]
    total_combinations = len(sample_sizes) * len(thresholds) * len(seeds)
    
    configs_per_job = total_combinations // 24
    remainder = total_combinations % 24
    
    print(f"Total experiment combinations: {total_combinations}")
    print(f"Training sizes: {sample_sizes}")
    print(f"Distribution: {remainder} jobs get {configs_per_job + 1} configs, {24 - remainder} jobs get {configs_per_job} configs")
    
    if args.idx < remainder:
        expected_configs = configs_per_job + 1
    else:
        expected_configs = configs_per_job
    print(f"Job {args.idx} expected to process: {expected_configs} configurations")
    
    # Get combinations for this job
    combinations = get_job_combinations(args.idx)
    
    if not combinations:
        print(f"No combinations assigned to job {args.idx}")
        return
    
    print(f"Actually processing {len(combinations)} configurations:")
    for sample_size, threshold, seed in combinations:
        print(f"  Samples: {sample_size}, Threshold: {threshold}, Seed: {seed}")
    
    # Train each combination using the shared dataset and config
    results_summary = []
    for i, (sample_size, threshold, seed) in enumerate(combinations):
        print(f"\n--- Configuration {i+1}/{len(combinations)} ---")
        try:
            result = train_single_config(sample_size, threshold, seed, args, dataset, config)
            if result:
                results_summary.append(result)
        except Exception as e:
            print(f"Error training samples={sample_size}, threshold={threshold}, seed={seed}: {e}")
            continue
    
    print(f"\n" + "=" * 80)
    print(f"Job {args.idx} completed!")
    print(f"Successfully processed {len(results_summary)} configurations")
    
    print(f"Results saved to: {args.output_dir}")
    print("CSV files contain epoch-by-epoch metrics for analysis")

if __name__ == "__main__":
    main()